version: '3'

services:

  client:
    build: .
    working_dir: /app/client
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/client/node_modules

  server:
    build: .
    working_dir: /app/server
    command:
      sh -c 'npx prisma migrate dev --name init; npm run start:dev'
    ports:
      - "3030:3030"
      - "5555:5555"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/server/node_modules

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: datecalc
      TZ: 'Asia/Tokyo'
    # volumes:
      # - ./docker/db/data:/var/lib/mysql
      # - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      # - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 6s
      retries: 10